<?php

namespace App\Dtos\PaystackDtos\DVADto;

class Customer
{
    /**
     * @var int The unique ID of the customer.
     */
    public $id;

    /**
     * @var string The first name of the customer.
     */
    public $first_name;

    /**
     * @var string The last name of the customer.
     */
    public $last_name;

    /**
     * @var string The email address of the customer.
     */
    public $email;

    /**
     * @var string The unique customer code generated by Paystack.
     */
    public $customer_code;

    /**
     * @var string The phone number of the customer.
     */
    public $phone;
}
