services:
  digitwhale_pva_backend:
    build: .
    env_file:
      - .env.prod
    restart: always
    # volumes:
      # - ./php/local.ini:/usr/local/etc/php/conf.d/local.ini
    ports:
      - "8000:8000"
    depends_on:
      - redis
    networks:
      - digitwhale-network

  redis:
    image: redis:alpine
    container_name: redis_server
    restart: always
    networks:
      - digitwhale-network

networks:
  digitwhale-network:
    external: true
