services:
  digitwhale_pva_backend:
    build: .
    env_file:
      - .env.prod
    restart: always
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./php/local.ini:/usr/local/etc/php/conf.d/local.ini
    ports:
      - "8000:8000"  # Octane listens here
    environment:
      APP_ENV: production
      APP_DEBUG: false
      APP_KEY: ${APP_KEY}
      DB_CONNECTION: mysql
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_DATABASE: ${DB_DATABASE}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      REDIS_HOST: redis
    depends_on:
      - redis
    command: php artisan octane:start --server=swoole --host=0.0.0.0 --port=8000
    networks:
      - digitwhale-network

  redis:
    image: redis:alpine
    container_name: redis_server
    restart: always
    networks:
      - digitwhale-network

networks:
  digitwhale-network:
    external: true
