version: '3.3'

services:
  digitwhale_pva_backend:
    image: ghcr.io/whales-group/digitwhale_pva_backend:main
    ports:
      - "9000:80"
    restart: always
    env_file:
      - .env.prod
    networks:
      - digitwhale_network

networks:
  digitwhale_network:
    driver: bridge