version: '3.8'
services:
  pva:
    build: .
    container_name: digitwhale_pva
    ports:
      - "127.0.0.1:8001:80"
    volumes:
      - ./:/var/www/html
    env_file:
      - .env.prod
    restart: unless-stopped
    networks:
      - digitwhale_net

networks:
  digitwhale_net:
    external: true