services:
  digitwhale_pva_backend:
    image: ghcr.io/whales-group/digitwhale_pva_backend:main
    ports:
      - "8080:8080"
    restart: always
    extra_hosts:
      - "host.docker.internal:host-gateway"
    env_file:
      - ./.env.prod
