version: '3.3'

services:
  digitwhale_pva_backend:
    # container_name: digitwhale_pva_backend_app
    image: ghcr.io/whales-group/digitwhale_pva_backend:main
    restart: always
    extra_hosts:
      - "host.docker.internal:host-gateway"
    env_file:
      - .env.prod
    environment:
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT:-3306}
      - DB_DATABASE=${DB_DATABASE}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
    volumes:
      - .:/var/www/html/digitwhale_pva_backend
    expose:
      - "9000"
    networks:
      - digitwhale_network
    healthcheck:
      test: ["CMD", "php", "artisan", "queue:work", "--once"]

  nginx:
    image: nginx:1.25.1-alpine
    restart: always
    ports:
      - "80:80"
      # - 443:443
    volumes:
      # - /data/certbot/www/:/var/www/certbot/
      # - /data/certbot/letsencrypt/:/etc/letsencrypt/
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - digitwhale_pva_backend
    networks:
      - digitwhale_network
    command: '/bin/sh -c ''while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g "daemon off;"'''

networks:
  digitwhale_network:
    driver: bridge
