<?php

namespace App\Common\Enums;

enum TransferType: string
{
    case SAME_CURRENCY_PAYOUT = 'SAME_CURRENCY_PAYOUT';
    case CROSS_CURRENCY_PAYOUT = 'CROSS_CURRENCY_PAYOUT';
    case BANK_ACCOUNT_TRANSFER = 'BANK_ACCOUNT_TRANSFER';
    case MOBILE_MONEY_PAYOUT = 'MOBILE_MONEY_PAYOUT';
    case FINCRA_ACCOUNT_TO_ACCOUNT_TRANSFER = 'FINCRA_ACCOUNT_TO_ACCOUNT_TRANSFER';
}