name: Deploy Laravel App via FTP to SERVER

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.2"
          extensions: mbstring, bcmath, curl, xml, tokenizer, pdo, pdo_mysql
          coverage: none

      - name: Cache Composer dependencies
        uses: actions/cache@v3
        with:
          path: vendor
          key: ${{ runner.os }}-php-${{ hashFiles('composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-

      - name: Install Composer Dependencies
        run: composer install --no-dev --optimize-autoloader

      - name: Check if composer.lock has changed
        id: check_lock
        run: |
          git fetch origin main
          if git diff --name-only HEAD^ HEAD | grep -q "composer.lock"; then
            echo "composer_changed=true" >> $GITHUB_OUTPUT
          else
            echo "composer_changed=false" >> $GITHUB_OUTPUT
          fi

      - name: Upload Laravel App via FTP (excluding vendor/)
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./
          server-dir: ${{ secrets.FTP_PATH }}
          exclude: |
            **/.git*
            **/node_modules/**
            **/tests/**
            **/storage/**
            **/vendor/**
            .github/
          dry-run: false
          dangerous-clean-slate: false

      - name: Upload Laravel Vendor Directory if composer.lock changed
        if: steps.check_lock.outputs.composer_changed == 'true'
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: vendor/
          server-dir: ${{ secrets.FTP_PATH }}/vendor/
          dry-run: false
          dangerous-clean-slate: false
